export type OperationMode =
  | 'addition'
  | 'subtraction'
  | 'multiplication'
  | 'division'
  | 'mixed'
  | 'custom'
  | 'true_false_math'
  | 'square_root'
  | 'fractions'
  | 'percentage'
  | 'algebra'
  | 'speed_math'
  | 'logic_puzzle'

